### ISSUE TITLE
Koken cannot locate the GD, ImageMagick, or GraphicsMagick library

### ISSUE THREAD

**Issue by fbrinker** [nicokaiser/docker-koken#2]
I get the following error when launching the installer:
```
Koken cannot locate the GD, ImageMagick, or GraphicsMagick library on your server.

We looked for ImageMagick and GraphicsMagick in the following locations: $PATH, /usr/bin, /usr/local/bin, /usr/local/sbin, /bin, /opt/local/bin, /opt/ImageMagick/bin, /usr/local/ImageMagick/bin.
```

Any ideas on this?

I've checked the installation and it looks fine for me:
```
graphicsmagick is already the newest version (1.3.30+hg15796-1~deb9u2).
graphicsmagick-imagemagick-compat is already the newest version (1.3.30+hg15796-1~deb9u2).
```

And the `convert` tool is placed in `/usr/bin`

My docker-compose file:

> version: '2'
> services:
> 
>   koken:
>     image: nicokaiser/koken
>     networks:
>       - web
>       - internal
>     volumes:
>       - ./html:/var/www/html
>     depends_on:
>       - mysql
>     labels:
>       - traefik.enable=true
>       - traefik.port=80
>       - traefik.backend=koken
>       - traefik.frontend.rule=Host:koken.mydomain.de
> 
>   mysql:
>     image: mariadb
>     networks:
>       - internal
>     environment:
>       MYSQL_ROOT_PASSWORD: very-secret-password
> 
> networks:
>   web:
>     external: true
>   internal:
>     external: true

**Comment by vdobrikov** [comment]
Same for me

**Comment by Gerr-Alt** [comment]
Same problem.

**Comment by tehniemer** [comment]
Count me in for this problem

**Comment by smnssn** [comment]
And for me.

**Comment by 3th3r** [comment]
Same here, need to manually install imagemagick inside the container. 
It would be great to upload a patched version of this image.

**Comment by nicokaiser** [comment]
Strange, this should work with the `graphicsmagick-imagemagick-compat` package, and as @fbrinker  said, 

@fbrinker Could you try one thing: in your volume (`./html`), add (or modify) a file `storage/configuration/user_setup.php` with the following content:

```
<?php
define('MAGICK_PATH', 'convert');
```

If this helps, I might need to adjust some paths. If not, I'll merge #3 for now, to at least have GD as a library available...

**Comment by mashb1t** [comment]
Still getting errors in the frontend when calling i.php

```Fatal error: Uncaught Error: Call to undefined function imagecreatefromjpeg() in /var/www/html/app/koken/Darkroom/DarkroomGD2.php:128 Stack trace: #0 /var/www/html/app/koken/Darkroom/DarkroomGD2.php(39): DarkroomGD2->createSource() #1 /var/www/html/app/koken/Darkroom/Darkroom.php(249): DarkroomGD2->createImage() #2 /var/www/html/app/koken/Darkroom/Darkroom.php(64): Darkroom->askForImage() #3 /var/www/html/i.php(278): Darkroom->render() #4 {main} thrown in /var/www/html/app/koken/Darkroom/DarkroomGD2.php on line 128```

**Comment by mashb1t** [comment]
This solved the issue:
```
RUN apt-get install -y libjpeg62-turbo-dev
RUN docker-php-ext-configure gd --with-jpeg-dir=/usr/include/
RUN docker-php-ext-install gd
```

This approach uses GD instead of ImageMagick.

(closes https://github.com/nicokaiser/docker-koken/issues/5)

**Comment by fbrinker** [comment]
> @fbrinker Could you try one thing: in your volume (`./html`), add (or modify) a file `storage/configuration/user_setup.php` with the following content:

Oh sry missed that notification. Thanks for your reply. But I have to admit that I'm not using Koken anymore :)

@mash1t - are the first two lines necessary?
Then they should be added to https://github.com/nicokaiser/docker-koken/pull/3

**Comment by crameth** [comment]
any plans to release an updated image fixing this issue to dockerhub?

**Comment by nicokaiser** [comment]
I'll create a new image with GD enabled.
